package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setListTitle(java.lang.String listTitle) {
		set("list_title", listTitle);
	}

	public java.lang.String getListTitle() {
		return get("list_title");
	}

	public void setNewsOrder(java.lang.Integer newsOrder) {
		set("news_order", newsOrder);
	}

	public java.lang.Integer getNewsOrder() {
		return get("news_order");
	}

	public void setListLink(java.lang.String listLink) {
		set("list_link", listLink);
	}

	public java.lang.String getListLink() {
		return get("list_link");
	}

	public void setListPic1Path(java.lang.String listPic1Path) {
		set("list_pic1_path", listPic1Path);
	}

	public java.lang.String getListPic1Path() {
		return get("list_pic1_path");
	}

	public void setListPic2Path(java.lang.String listPic2Path) {
		set("list_pic2_path", listPic2Path);
	}

	public java.lang.String getListPic2Path() {
		return get("list_pic2_path");
	}

	public void setListContent(java.lang.String listContent) {
		set("list_content", listContent);
	}

	public java.lang.String getListContent() {
		return get("list_content");
	}

	public void setListDate(java.util.Date listDate) {
		set("list_date", listDate);
	}

	public java.util.Date getListDate() {
		return get("list_date");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setHtmlTitle(java.lang.String htmlTitle) {
		set("html_title", htmlTitle);
	}

	public java.lang.String getHtmlTitle() {
		return get("html_title");
	}

	public void setHtmlKeywords(java.lang.String htmlKeywords) {
		set("html_keywords", htmlKeywords);
	}

	public java.lang.String getHtmlKeywords() {
		return get("html_keywords");
	}

	public void setHtmlDesc(java.lang.String htmlDesc) {
		set("html_desc", htmlDesc);
	}

	public java.lang.String getHtmlDesc() {
		return get("html_desc");
	}

	public void setReadCount(java.lang.Integer readCount) {
		set("read_count", readCount);
	}

	public java.lang.Integer getReadCount() {
		return get("read_count");
	}

	public void setPublishDate(java.util.Date publishDate) {
		set("publish_date", publishDate);
	}

	public java.util.Date getPublishDate() {
		return get("publish_date");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

	public void setModifiedDate(java.util.Date modifiedDate) {
		set("modified_date", modifiedDate);
	}

	public java.util.Date getModifiedDate() {
		return get("modified_date");
	}

}
